### PR TITLE
Changed site theme

### PR DESCRIPTION
**Pull request by nikauhrinova**
Redesigned the site. Let me know if some changes should be done.

### CODE REVIEW

**Comment by toms3t** [comment]
@nikauhrinova - I switched to your "theme-change" branch and tested your code. However, I see no theme difference, it all looks the same as the prod code. Can you review your code and let me know if there are any additional steps to view the theme difference?

**Comment by nikauhrinova** [comment]
I checked it and I have to say I'm not sure where the problem could be, the site shown on the screenshot is from the "theme-change" branch.

Screenshot (316)

**Comment by toms3t** [comment]
@nikauhrinova - got your theme to load. I like your theme but have a few suggestions:
- Home page looks great. Can you horizontally center the "(*) from Zillow.com" text?
- Maybe add some color to the home, input, and results pages? The same color on the header of each page would look good.
- The text on the results page may be too large. I'm wondering how this will look on mobile phones - I'll look into loading this into a dev slot of the web app to test the theme on mobile.

Great work!

**Comment by nikauhrinova** [comment]
Thanks! I'll work on your suggestions and I'll look more into responsivity of the theme.

**Comment by toms3t** [comment]
@nikauhrinova - merging your branch into a new "theme-change" branch to deploy into a dev web app. Will test on mobile and let you know. Thanks!

**Comment by toms3t** [comment]
@nikauhrinova - https://propalyzer-dev.azurewebsites.net/

**Pull request merged**
