### PR TITLE
Enhancement/refactoring

### PR DESCRIPTION
**Pull request by Nitsujed**
#94  The cleans up the view file to take out all the logic that was being performed and much more simplified.

I duplicated some of the property logic to support a new file called context_data.py. I think we should use this class to handle the calculations and non-API necessary work. We can pass data back and forth between the deeper pages without having to unnecessarily call APIs again.

### CODE REVIEW

**Comment by toms3t** [comment]
@Nitsujed Awesome! thanks for the refactor. I'm introducing CI/CD for this app through Azure Pipelines such that any update to the master branch will trigger a new build and new release. I should have that done today. Next up, will get your PR reviewed ASAP.

**Comment by Nitsujed** [comment]
@toms3t I branched from master which didn't have the pdf pulled in yet. So if you are good with this merge, I will pull the changes into the pdf branch and submit a new request once it's cleaned up. Also, I think I still want to do more cleanup, so I will prob leave this branch open for continued repairs.

**Comment by toms3t** [comment]
@Nitsujed sounds good on the PDF merge. You can ignore that PR that just came through from the azure-pipelines branch, just testing things out.

**Comment by toms3t** [comment]
@Nitsujed - got CI/CD working in Azure Pipelines. Also, pulled your code in and ran through the typical use cases with no problems. Let's merge this with your PDF feature into a single PR like we discussed. Also, can you update 'test_property.py' so that we have updated tests based on the new code? The tests will have to pass before the merge into master. Thanks for your work on this!

**Comment by Nitsujed** [comment]
As discussed above, I am going to initiate a new pull request.

**Pull request closed without merging**
